spring.mongodb.uri=mongodb://localhost:27017/projecte3_db
spring.mongodb.database=projecte3_db

# Opcional: veure les consultes MongoDB a la consola
logging.level.org.springframework.data.mongodb=DEBUG